Repository getmoto/moto, pull requests merged in 2022-10, with the labels that each got.

#5528 Include actual previous state in EC2 instance state-change actions
  moto/ec2/models/instances.py
  moto/ec2/responses/instances.py
  tests/test_ec2/test_instances.py
Labels: hacktoberfest-accepted

#5521 Improve DDB transaction validation
  moto/dynamodb/exceptions.py
  moto/dynamodb/models/__init__.py
  tests/test_dynamodb/exceptions/test_dynamodb_exceptions.py
Labels: hacktoberfest-accepted

#5532 Fix invalid escape sequence, enable pylint check
  moto/s3/responses.py
  setup.cfg
Labels: hacktoberfest-accepted

#5533 Fix glue expression
  moto/glue/models.py
  tests/test_glue/test_datacatalog.py
Labels: hacktoberfest-accepted

#5536 Implement mediaconnect flow entitlement methods
  IMPLEMENTATION_COVERAGE.md
  docs/docs/services/mediaconnect.rst
  moto/mediaconnect/models.py
  moto/mediaconnect/responses.py
  moto/mediaconnect/urls.py
  tests/test_mediaconnect/test_mediaconnect.py
Labels: hacktoberfest-accepted

#5538 Implement update_flow_output
  IMPLEMENTATION_COVERAGE.md
  docs/docs/services/mediaconnect.rst
  moto/mediaconnect/models.py
  moto/mediaconnect/responses.py
  tests/test_mediaconnect/test_mediaconnect.py
Labels: hacktoberfest-accepted

#5539 Make available logStreamName key when a job is running
  moto/batch/models.py
Labels: hacktoberfest-accepted

#5541 Feature: Metering Marketplace
  IMPLEMENTATION_COVERAGE.md
  docs/docs/services/meteringmarketplace.rst
  moto/__init__.py
  moto/backend_index.py
  moto/meteringmarketplace/__init__.py
  moto/meteringmarketplace/exceptions.py
  moto/meteringmarketplace/models.py
  moto/meteringmarketplace/responses.py
  moto/meteringmarketplace/urls.py
  tests/test_meteringmarketplace/test_meteringmarketplace.py
Labels: hacktoberfest-accepted

#5540 TechDebt - MyPy the ACM module
  Makefile
  moto/acm/exceptions.py
  moto/acm/models.py
  moto/acm/responses.py
  moto/acm/utils.py
  moto/core/exceptions.py
  moto/elb/models.py
  moto/elbv2/models.py
  tests/test_acm/test_acm.py
Labels: hacktoberfest-accepted

#5531 Prettify responses
  docs/docs/configuration/index.rst
  docs/docs/configuration/prettify_responses.rst
  moto/core/responses.py
  moto/settings.py
  tests/test_core/test_responses.py
Labels: hacktoberfest-accepted, moto-core

#5549 TechDebt: Enable MyPy on APIGateway-module
  IMPLEMENTATION_COVERAGE.md
  Makefile
  docs/docs/services/apigateway.rst
  moto/apigateway/exceptions.py
  moto/apigateway/integration_parsers/__init__.py
  moto/apigateway/integration_parsers/aws_parser.py
  moto/apigateway/integration_parsers/http_parser.py
  moto/apigateway/integration_parsers/unknown_parser.py
  moto/apigateway/models.py
  moto/apigateway/responses.py
  moto/apigateway/utils.py
  moto/core/common_models.py
  moto/core/utils.py
  moto/utilities/utils.py
  setup.cfg
  tests/test_apigateway/test_apigateway.py
Labels: moto-core

#5550 Add RDS modify_db_cluster()
  IMPLEMENTATION_COVERAGE.md
  moto/rds/models.py
  moto/rds/responses.py
  tests/test_rds/test_rds_clusters.py
Labels: hacktoberfest-accepted

#5553 Create multiplatform docker image that also runs on m1 macbooks
  .github/workflows/release.yml
Labels: hacktoberfest-accepted

#5577 docs: Patching services not supported
  docs/docs/services/patching_other_services.rst
  docs/index.rst
Labels: hacktoberfest-accepted

#5575 Initial implementation of list_invalidations() for cloudfront.
  moto/cloudfront/models.py
  moto/cloudfront/responses.py
  tests/test_cloudfront/test_cloudfront_invalidation.py
Labels: hacktoberfest-accepted

#5559 IAM:detach_*_policy(): Fix divergent error handling with aws
  moto/iam/models.py
  tests/test_iam/test_iam.py
Labels: hacktoberfest-accepted

#5619 Admin: Enable support for Py 3.11
  .github/workflows/build.yml
  .github/workflows/dockertests.yml
  .github/workflows/test_outdated_versions.yml
  .github/workflows/test_terraform.yml
  codecov.yml
  setup.py
Labels: moto-core
